### ISSUE TITLE
ENH: Profile and Speed Up Code

### ISSUE THREAD

**Issue by buddejul** [buddejul/pyvmte#20]
- [ ] Profile code using EPP tools.
- [ ] Speed up bottlenecks using either Numba or jax.

**Comment by buddejul** [comment]
`monte_carlo_pyvmte` actually spends a significant amount of time _simulating_ the data, especially for smaller simulations like `sample_size = 1_000` (roughly 50% in data simulation and 50% in estimation!).

within estimation, time is split roughly half between the two LPs
- both LPs spend most time on building the ub matrix

#### Todos
- improve `simulate_data_from_dgp`
- improve building `A_ub` matrix

**Comment by buddejul** [comment]
For `sample_size = 100_000` the split between estimation and data simulation is more like 80:20 and almost all time in estimation is spent in estimating the weights.

**Comment by buddejul** [comment]
<img width="937" alt="image" src="https://github.com/buddejul/pyvmte/assets/66945206/560c3481-07f1-438d-bc6a-b5083802d6c5">

**Comment by buddejul** [comment]
Current state with `sample_size = 100_000` and `reps = 1_000` after implementing significant gamme_estimation speedups.

<img width="698" alt="image" src="https://github.com/buddejul/pyvmte/assets/66945206/c2a35635-7d4b-494d-9cbd-0c99204a4532">

**Comment by buddejul** [comment]
Currently, most gains come from 
- Weight estimation: exiting early when results known to be 0 and optimizing computation for remaining cases
- Moving repetitive steps (e.g. computing instrument characteristics) to higher level
- More efficient sampling for data

Todo 
- [ ] Optimize bern_bas computation: Lot of time spent in simulating data most of which in `bern_bas`
- [ ] For large samples instrment `_estimate_instrument_characteristics` takes up a lot of time
